package com.defusername.bookworm.model;

public enum BookCategory {

	ACTION_AND_ADVENTURE,
	BUSINESS,
	CLASSICS,
	COMICS_AND_GRAPHIC_NOVEL,
	DETECTIVE_AND_MYSTERY,
	FANTASY,
	EDUCATION_AND_REFERENCES,
	HISTORY,
	HORROR,
	LITERARY_FICTION,
	ROMANCE,
	SCIENCE_FICTION,
	SHORT_STORIES,
	THRILLERS,
	BIOGRAPHIES_AND_AUTOBIOGRAPHIES,
	MANUALS,
	ESSAYS,
	POETRY,
	SELF_IMPROVEMENT,
	SCIENCE_AND_MATH
}
